### PR TITLE
Refactored the Enemy Class to be more useful

### PR DESCRIPTION
**Pull request by jrembold**
It seemed to me that in order to get some more interesting enemies going, and to improve flexibility, it might be helpful to have the enemy logic split out more into its own class. So here I've broken out the basics into a base class, and then created 4 different "flavors" of enemies as subclasses. I've gone ahead and taken the liberty of replacing the original enemies in the levels with similar ones based off the new Enemy structure.

Also merged your lives update with this, so both seem to be fully in agreement!

I tried to give the enemies plenty of options to increase their difficulty, so maybe new levels can be created on the fly based off the players score? That way 15 wouldn't always be the high score?

I stayed up too late working on this, but I way grading all day and needed a break. Let me know if you need help merging this pull request, but I think it should be fairly self explanatory. :smile: :+1::+1:

### CODE REVIEW

**Comment by jrembold** [comment]
Oh yeah, and I tweaked a little with the textures so that the gun barrel is facing the same direction as `self.angle` now so that weird correction factors don't have to be made in the bullet firing. :octopus:

**Comment by lostiles13** [comment]
OH I SYNCED THIS TO MY OTHER EMAIL NOW I SEE THESE

**Comment by lostiles13** [comment]
REMBOLD THANK YOU FOR BEING SO INVOLVED IN THIS IM SO SO HAPPY

**Comment by lostiles13** [comment]
could you explain a little more on what you mean by based on their score
the levels will increase?

right now I am creating a method that has more to do with taking an input
value (level number) and then see what mod it is and depending on that it
will execute a different level pattern
( right now i have stationary, moving) and then increasingly difficult
levels that will make bullets bounce off the walls and stuff.  Does that
make sense? I would love to understand your vision too

**Comment by jrembold** [comment]
Yeah yeah, that's very along the lines of what I was thinking. Level number or current score, both would be increasing as they progress, so I think either could be a way to keep track and generate progressively harder levels.

I just finished with my grading so I'll take a look at what the latest and greatest is now :)

**Pull request merged**
